theme: jekyll-theme-midnight
title: 
description:This is the webpage for the Cryptography Reading Group at George 
Mason University. We meet weekly to discuss foundational topics, classical 
results and emerging ideas in cryptography.

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - readme.md